name: API CI
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Build
        run: dotnet build

  publish-nuget:
    runs-on: ubuntu-latest
    name: Nuget Publish
    needs: [test]
    # tag a release as v1.0.0....
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Install dependencies
        run: dotnet restore

      - name: Extract tag version
        shell: pwsh
        run: |
          $env:GITHUB_REF -match "^refs/tags/v(.+)"
          $versionTag = $Matches[1]
          echo "VERSION_TAG=$versionTag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Pack
        run: dotnet pack EmmaSharp --configuration Release -p:PackageVersion=$VERSION_TAG -p:IncludeSymbols=true --output artifacts

      - name: Publish
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_SYMBOL_SOURCE: ${{ secrets.NUGET_SYMBOL_SOURCE }}        
          NUGET_ACCESS_TOKEN: ${{ secrets.NUGET_ACCESS_TOKEN }}
        run: |
          dotnet nuget push artifacts/*.nupkg \
            --api-key $NUGET_ACCESS_TOKEN \
            --source $NUGET_SOURCE \
            --skip-duplicates \
            --symbol-source $NUGET_SYMBOL_SOURCE \
            --symbol-api-key $NUGET_ACCESS_TOKEN
